[package]
name = "eternity-ii"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
bitint = "0.1"
bitvec = "1"
mvbitfield = "0.2"
num-format = { version = "0.4", features = ["with-system-locale"] }
rayon = "1"
strum = { version = "0.25", features = ["derive"] }
